apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: emptyjobs.tsemach.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: tsemach.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                jobName:
                  type: string                
                
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    kind: EmptyJob
    singular: emptyjob
    plural: emptyjobs
    shortNames:
      - emptyjobs
