# permissions for end users to view emptyjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: emptyjob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: emptyjob-contoroller
    app.kubernetes.io/part-of: emptyjob-contoroller
    app.kubernetes.io/managed-by: kustomize
  name: emptyjob-viewer-role
rules:
- apiGroups:
  - tsemach.org.my.domain
  resources:
  - emptyjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tsemach.org.my.domain
  resources:
  - emptyjobs/status
  verbs:
  - get
